---
apiVersion: v1
kind: Pod
metadata:
  name: dbpod
spec:
  containers:
  - image: mohamedelmowafy/vprofiledb:V1
    name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: db-vol
  volumes:
  - name: db-vol
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: DirectoryOrCreate
